### ISSUE TITLE
Debian 10 desktop startup seems incomplete with no menu available

### ISSUE THREAD

**Issue by mikedlr** [sdarwin/Ansible-VNC#18]
1) setup an AWS system based on the official Debian 10 AMI image and install this role on it 
2) login via SSH with port forwarding starting the VNC session
3) connect to the VNC desktop

Actual result:

There is a terminal window and a VNC window with window decorations but the normal desktop applicatinon menu is not avialble via any of - press windows key / left or right click on desktop / select a toolbar (none visible) 

Expected result

A compete session with applications available.

**Comment by mikedlr** [comment]
if there is no xstartup file and the VNC server is reastarted (then the desktop session works fine - normal Gnome session - but does *not* create an xstartup file 

```
./vncstop.sh
./vncstart.sh
```

**Comment by sdarwin** [comment]
This appears to solve the problem, regardless of xstartup:

```
./vncstop.sh
./vncstart.sh
```

The menus reappear.  

Removing xstartup does generate a different desktop appearance.

**Comment by mikedlr** [comment]
If I am running the second VNC server (port 5902) from the admin account then the workaround shown doesn't fix the problem.

**Comment by sdarwin** [comment]
Added this to Debian 10:

```
default_xstartup_additional_command1: "dbus-update-activation-environment --systemd --all"
```

based on some quick testing, seems to be fixed.

**Comment by sdarwin** [comment]
As mentioned in previous comment, default_xstartup_additional_command1 has been added to the vars file.   It did seem to solve the issue.  Therefore, closing the ticket.   Can be re-opened, if necessary.
