### ISSUE TITLE
VNC with root user

### ISSUE THREAD

**Issue by xrow** [sdarwin/Ansible-VNC#20]
My hope was to use root user too. Maybe that is not smart.

```
TASK [sdarwin.vnc : add vncstart.sh to .bashrc for each user] ************************************
failed: [server005.dc02.XXX.net] (item={'username': 'root', 'usergroup': 'root', 'vnc_num': 1, 'vnc_default_password': 'centos'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "usergroup": "root",
        "username": "root",
        "vnc_default_password": "centos",
        "vnc_num": 1
    },
    "rc": 257
}

MSG:

Destination /home/root/.bashrc does not exist !
```

**Comment by sdarwin** [comment]
This role is making an assumption that the user's home directory is "/home/{{ item.username }}", which isn't always correct.  root's home directory is /root.

A solution in the linux shell could be: 

```
homedir=$( getent passwd "{{ item.username }}" | cut -d: -f6 )
```
There might be another way using jinja/python/ansible.  Or, simply leverage the shell.

Early in the list of tasks, a loop could analyze all users, and set a variable for each one which is their item.homedir, to accompany item.username.   The info will be available during the rest of the processing.

Would you like to send a pull request?  :-)

Typically, you don't ssh as root.  You ssh as another user, and then sudo.

**Comment by xrow** [comment]
If you do not hear from me please close in 7 days. Ty.
