### ISSUE TITLE
TigerVNC on Ubuntu 16 with vnc_install_systemd_services set is broken

### ISSUE THREAD

**Issue by jackm** [sdarwin/Ansible-VNC#21]
When running this role on an Ubuntu 16 host and when variable `vnc_install_systemd_services` is true, the generated systemd service file will be referencing an non-existent binary path.

Failed task output is:

```
TASK [sdarwin.vnc : systemctl start] ***********************************************************************************************************************************************************************************************
failed: [localhost] (item={'username': 'user', 'group': 'user', 'vnc_num': 1, 'vnc_default_password': 'XXX'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "su -c 'XDG_RUNTIME_DIR=\"/run/user/$(id -u)\" DBUS_SESSION_BUS_ADDRESS=\"unix:path=${XDG_RUNTIME_DIR}/bus\" systemctl --user start vncserver' user", "delta": "0:00:00.040629", "end": "2022-01-12 21:12:53.992957", "item": {"group": "user", "username": "user", "vnc_default_password": "XXX", "vnc_num": 1}, "msg": "non-zero return code", "rc": 1, "start": "2022-01-12 21:12:53.952328", "stderr": "Job for vncserver.service failed because the control process exited with error code. See \"systemctl --user status vncserver.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Job for vncserver.service failed because the control process exited with error code. See \"systemctl --user status vncserver.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}
```

When TigerVNC is installed, the systemd service file included in the downloaded package deb references binary `/usr/lib/x86_64-linux-gnu/vncsession-start` instead of `/usr/bin/vncserver` which is what this role's systemd service template file references.

**Comment by sdarwin** [comment]
Hi jackm,
To test this scenario, I launched an new Ubuntu 16 host on AWS, and only changed this variable, nothing else:

```
vnc_install_systemd_services: true
```
Installed the role. It works. What might you be doing that different from the above?  

The error you posted says more information is available in  "systemctl --user status vncserver.service" and "journalctl -xe".   Could you post that additional information?  And, if you run `ls -al /usr/bin/vncserver`

How do things look if you reboot the machine? Actually, one reboot is required after running this ansible role using vnc_install_systemd_services.

---

It's interesting to solve the error, and hopefully we can continue to probe into it a little.

However, you should also be aware 
1. Ubuntu 16 is end-of-support-life , and because of that, not the best selection of an operating system.
2. The vnc_install_systemd_services variable isn't required.   You could leave it as "false".  The newest versions of Ubuntu and Tiger are going to solve the systemd issue using an entirely different methodology, and so vnc_install_systemd_services will become an obsolete way of handling it.

**Comment by jackm** [comment]
The binary referenced in the systemd service file does not exist on the host:

```
$ systemctl --user cat vncserver.service 
# /home/vagrant/.config/systemd/user/vncserver.service
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
PAMName=login
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill :1 > /dev/null 2>&1 || :'
ExecStart=/usr/bin/vncserver :1 -geometry 1280x720 -localhost 
ExecStop=/usr/bin/vncserver -kill :1

[Install]
WantedBy=default.target
```

```
$ ls /usr/bin/vncserver
ls: cannot access '/usr/bin/vncserver': No such file or directory
```

This is the cause of the `systemctl start` task failing.

I am using the vagrant box image [`geerlingguy/ubuntu1604`](https://app.vagrantup.com/geerlingguy/boxes/ubuntu1604). After deploying with vagrant, I then run this playbook:

```
---

- hosts: ubuntu1604
  become: yes
  roles:
    - role: sdarwin.vnc
      vnc_install_systemd_services: true
      vnc_users:
        - username: vagrant
          vnc_default_password: vagrant
          vnc_num: 1
```

Task `systemctl start` fails. Rebooting does not change the contents of the systemd unit file and so the failure persists.

**Comment by sdarwin** [comment]
It's mysterious.  Various templates in the ansible role (with or without vnc_install_systemd_services) depend on the existence of /usr/bin/vncserver.   How about trying a new install on ubuntu 18.04 https://app.vagrantup.com/geerlingguy/boxes/ubuntu1804

Set

```
vnc_install_systemd_services: false
```

Carefully monitor ansible to see if it displays any warnings or errors.

Run this after the install:

```
locate vncserver
```

**Comment by jackm** [comment]
Running the role on an Ubuntu 18.04 host with `vnc_install_systemd_services` set to false (default value) does work as expected.

VNC server is started without failures:

```
$ ps -fp $(pgrep vnc)
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
vagrant  10292     1  0 15:22 ?        Sl     0:00 /usr/bin/Xtigervnc :1 -desktop testserver:1 (vagrant) -auth /home/vagrant/.Xauthority -geometry 1280x720 -depth 24 -rfbwait 30000 -rfbauth /home/vagrant/.vnc/passwd -rfbport 5901 -pn -loc
vagrant  10312     1  0 15:22 ?        S      0:00 vncconfig -iconic
```

When `vnc_install_systemd_services` set to true, the systemd service is also started correctly on an Ubuntu 18.04 host. `/usr/bin/vncserver` becomes a symlink to the TigerVNC binary.

```
$ ls -l /usr/bin/vncserver
lrwxrwxrwx 1 root root 27 Jan 14 15:22 /usr/bin/vncserver -> /etc/alternatives/vncserver
$ ls -l /etc/alternatives/vncserver
lrwxrwxrwx 1 root root 23 Jan 14 15:22 /etc/alternatives/vncserver -> /usr/bin/tigervncserver
$ readlink -f /usr/bin/vncserver
/usr/bin/tigervncserver
```

The binary file `/usr/bin/tigervncserver` is owned by package `tigervnc-standalone-server` which comes from the official Ubuntu universe apt repo:

```
$ dpkg -S /usr/bin/tigervncserver
tigervnc-standalone-server: /usr/bin/tigervncserver
$ apt policy tigervnc-standalone-server
tigervnc-standalone-server:
  Installed: 1.7.0+dfsg-8ubuntu2
  Candidate: 1.7.0+dfsg-8ubuntu2
  Version table:
 *** 1.7.0+dfsg-8ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

This is only an issue on Ubuntu 16.04 where the TigerVNC package deb is downloaded and installed manually in separate Ansible tasks. When this happens, the file `/usr/bin/vncserver` doesn't exist and/or doesn't get symlinked to the actual TigerVNC binary properly. Your systemd unit file template assumes that the file `/usr/bin/vncserver` will exist even on an Ubuntu 16.04 host.

**Comment by sdarwin** [comment]
Ran another test in docker.
```
docker run -it ubuntu:16.04
```

Downloaded the tiger installer manually. Installed it manually.  During the process, it shows this step:
```
Setting up tigervncserver (1.10.1-1ubuntu1) ...
update-alternatives: using /usr/bin/tigervncserver to provide /usr/bin/vncserver (vncserver) in auto mode
update-alternatives: using /usr/bin/Xtigervnc to provide /usr/bin/Xvnc (Xvnc) in auto mode
update-alternatives: using /usr/bin/x0tigervncserver to provide /usr/bin/x0vncserver (x0vncserver) in auto mode
update-alternatives: using /usr/bin/tigervncpasswd to provide /usr/bin/vncpasswd (vncpasswd) in auto mode
update-alternatives: using /usr/bin/tigervncconfig to provide /usr/bin/vncconfig (vncconfig) in auto mode
```
and thus, /usr/bin/vncserver exists.

How about testing bento box vagrant? 
https://app.vagrantup.com/bento/boxes/ubuntu-16.04

**Comment by jackm** [comment]
Using vagrant box [bento/ubuntu-16.04](https://app.vagrantup.com/bento/boxes/ubuntu-16.04) still fails.

`/etc/alternatives/vncserver` points to the correct TigerVNC binary but `/usr/bin/vncserver` still doesn't exist:

```
$ ls -l /usr/bin/vncserver
ls: cannot access '/usr/bin/vncserver': No such file or directory
$ ls -l /etc/alternatives/vncserver
lrwxrwxrwx 1 root root 40 Jan 14 19:14 /etc/alternatives/vncserver -> /usr/lib/x86_64-linux-gnu/tigervncserver
```

`tigervncserver` is the name of the package installed by [tigervncserver_1.11.0-1ubuntu1_amd64.deb](https://downloads.sourceforge.net/project/tigervnc/stable/1.11.0/ubuntu-16.04LTS/amd64/tigervncserver_1.11.0-1ubuntu1_amd64.deb) (set by `default_vnc_tiger_url` role variable). This is the one used in this role when run on an Ubuntu 16 host.

```
$ apt policy tigervncserver
tigervncserver:
  Installed: 1.11.0-1ubuntu1
  Candidate: 1.11.0-1ubuntu1
  Version table:
 *** 1.11.0-1ubuntu1 100
        100 /var/lib/dpkg/status
```

Is this the same deb package you used?

Interestingly, the `/usr/bin/vncserver` file is the only one missing out of the five binaries that are linked via `update-alternatives`:

```
$ ls -l /usr/bin/{vnc*,Xvnc,x0vncserver}
lrwxrwxrwx 1 root root 27 Jan 14 19:14 /usr/bin/vncconfig -> /etc/alternatives/vncconfig
lrwxrwxrwx 1 root root 27 Jan 14 19:14 /usr/bin/vncpasswd -> /etc/alternatives/vncpasswd
lrwxrwxrwx 1 root root 29 Jan 14 19:14 /usr/bin/x0vncserver -> /etc/alternatives/x0vncserver
lrwxrwxrwx 1 root root 22 Jan 14 19:14 /usr/bin/Xvnc -> /etc/alternatives/Xvnc
```

**Comment by sdarwin** [comment]
This ansible role doesn't ship with tigervncserver_1.11.0-1ubuntu1_amd64.deb , right?    

It specifies tigervncserver_1.10.1-1ubuntu1_amd64.deb 

The tiger packagers have updated the executable links.

Meanwhile, we only need to keep the ship afloat until Ubuntu 16.04 is obsolete (which is _already_ the situation because it's not supported.)

If you don't customize the deb package and use 1.10.1 it should work.   

Then, upgrade to ubuntu 18.04.  No download is done on ubuntu 18.04.

So, it's solved.

**Comment by jackm** [comment]
I am using `sdarwin.vnc` role [tag v1.0.0](../tree/v1.0.0) from Ansible galaxy (the latest one available). This version does not contain commit b8fe074 where you changed the `default_vnc_tiger_url` variable to point to a download url for _tigervncserver\_**1.10.1**-1ubuntu1\_amd64.deb_ (even though the commit message says "TigerVNC 1.11.0"). Tag v1.0.0 still has the download url set to _tigervncserver\_**1.11.0**-1ubuntu1\_amd64.deb_ in [Debian-family.yml:39](../blob/v1.0.0/vars/Debian-family.yml#L39). All of the testing has been using _tigervncserver\_1.11.0-1ubuntu1\_amd64.deb_.

Ubuntu 16.04 is not obsolete - standard support ended in April 2021 but it is not end-of-life until April 2026.

This role states that it [supports Ubuntu 16 (Xenial)](../tree/v1.0.0/meta/main.yml#L16) which is why I expected it to work.

**Comment by sdarwin** [comment]
Great feedback!  
Just added more tags:  
- v1.1.0  the newest version of the role
- v1.0.1 a bugfix to v1.0.0, which sets Ubuntu 16 back to using TigerVNC 1.10.1

At least for the time being this seems to be a reasonable compromise, everything will continue functioning as before.

**Comment by jackm** [comment]
I just tore down and respun an Ubuntu 16.04 image and then ran the same playbook but using sdarwin.vnc role v1.0.1 and confirmed that the playbook finishes without any failures and that the TigerVNC server systemd service is running.

**Comment by sdarwin** [comment]
@jackm thanks for the help!  

This demonstrates how the current molecule tests are too sparse, I will work on adding more test cases.
