### ISSUE TITLE
Publish new version to Ansible Galaxy

### ISSUE THREAD

**Issue by ION28** [sdarwin/Ansible-VNC#22]
When the repository was updated 6 months ago to add support for Ubuntu 22 Jammy, a new version was not published in Github. As a result, installs through Ansible Galaxy do not have support for Ubuntu 22. 

It would be great if you could publish a new version so this is supported without having to manually clone this repository. Thanks so much!

**Comment by sdarwin** [comment]
done, I think

**Comment by sdarwin** [comment]
@ION28 sorry about the mixup, I believe that without tags ansible galaxy will import the latest git commit and that is what I am accustomed to.   After tags exist, then you are forced to keep them updated.
