### ISSUE TITLE
Ubuntu 23 support

### ISSUE THREAD

**Issue by geiger-to** [sdarwin/Ansible-VNC#25]
Running this role on an Ubuntu 23 machine fails because it is unable to find `Ubuntu-23.yml`. Adding a copy of this repo's [`vars/Ubuntu-22.yml`](https://github.com/sdarwin/Ansible-VNC/blob/master/vars/Ubuntu-22.yml) to `vars/Ubuntu-23.yml` (locally) allows me to get past the initial error. I am still testing to see if this is enough to support Ubuntu 23.

PRs welcome? I'm happy to put one up.

**Comment by sdarwin** [comment]
> PRs welcome? I'm happy to put one up.

Ok
