### ISSUE TITLE
Publish new version to Ansible Galaxy

### ISSUE THREAD

**Issue by ION28** [sdarwin/Ansible-VNC#28]
When the repository was updated 8 months ago to add support for Ubuntu 24 Noble, a new tag was not published in Github. As a result, installs through Ansible Galaxy do not have support for Ubuntu 24 (or Ubuntu 23 either).

It would be great if you could publish add a new tag to the main branch, so this is supported without having to manually clone this repository. Thanks so much!

**Comment by sdarwin** [comment]
Other repos without tags don't have this issue - they track the `master` branch.  It's a shame I tagged this one.  :-)
Done.
